## IT2313 - Programming for Data Science
## Practical 4 
## NumPy for Numerical Computations (Part 2)

### In this lesson, we will continue to practise our NumPy knowledge. 
- Shapes and Operation
- Basic Math Operation
- Matrix and Manipulation
- Broadcasting
- Case Study with actual dataset

#### We need to import the neccessary libraries

In [2]:
import numpy as np

#### Q1 - Create an array with sequence of alternate numbers from 0 to 18 and save it to A

In [3]:
# Type your answer here
A = np.arange(0,18,2)
print(A)

[ 0  2  4  6  8 10 12 14 16]


#### Q2 - Print the shape of the array A

In [4]:
# Type your answer here
print(A.shape)

(9,)


#### Q3 - Create an array with sequence of numbers from 1 to 9 and save it to B, Reshape array B to a 3 by 3 array and display array B 

In [5]:
# Type your answer here
B = np.arange(1,10,1).reshape(3,3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Q4 - Print the shape of the array B

In [6]:
# Type your answer here
# Need to know to tell that this is a 2D Array
print(B.shape)

(3, 3)


#### Q5 - Let create the following arrays
[[0 1]
[2 3]]

[[10.1 13.4]
[15.5 21.3]]

In [14]:
# Type your answer here
x = np.array((0,1,2,3)).reshape(2,2)
y = np.array((10.1, 13.4, 15.5, 21.3)).reshape(2,2)
print(x)
print(y)

[[0 1]
 [2 3]]
[[10.1 13.4]
 [15.5 21.3]]


#### Q6 - Using the above array,
 - (a) sum up array x and y using the "+" operator and add function
 - (b) subtract array y from x using the "-" operator and subtract function
 - (c) multiply array x and y using the "*" operator and multiply function
 - (d) divide up y from x using the "/" operator and divide function

In [42]:
# Question Q6(a)
# Type your answer here

print(x + y)
print()
print(np.add(x,y))

[[10.1 14.4]
 [17.5 24.3]]

[[10.1 14.4]
 [17.5 24.3]]


In [46]:
# Question Q6(b)
# Type your answer here
print(x - y)
print()
print(np.subtract(x,y))

[[-10.1 -12.4]
 [-13.5 -18.3]]

[[-10.1 -12.4]
 [-13.5 -18.3]]


In [47]:
# Question Q6(c)
# Type your answer here

print(x * y)
print()
print(np.multiply(x,y))

[[ 0.  13.4]
 [31.  63.9]]

[[ 0.  13.4]
 [31.  63.9]]


In [39]:
# Question Q6(d)
# Type your answer here

print(x / y)
print()
print(np.divide(x,y))

[[0.         0.07462687]
 [0.12903226 0.14084507]]

[[0.         0.07462687]
 [0.12903226 0.14084507]]


#### Q7 - Let use the following command to generate a 5x5 matrix

mat = np.arange(1, 26).reshape(5, 5)
##### Flatten the array, shuffle it, and then reshape it back
flat_mat = mat.flatten()
np.random.shuffle(flat_mat)
mat = flat_mat.reshape(5, 5)

 - (a) Compute the mean, median, standard deviation of a numpy array in each of the rows
 - (b) Compute the mean, median, standard deviation of a numpy array in each of the columns
 - (c) Compite the mean, median, standard deviation for the matrix

In [24]:
# Set a random seed for reproducibility
# This is to ensure every run will produce the same random number
seed_value = 42
np.random.seed(seed_value)

mat = np.arange(1, 26).reshape(5, 5)
flat_mat = mat.flatten()
np.random.shuffle(flat_mat)
mat = flat_mat.reshape(5, 5)
print(mat)

[[ 9 17  1 24 12]
 [10 14  2 23  6]
 [ 3 13 16  4  5]
 [21 18 22 19 25]
 [ 8 11 15 20  7]]


In [55]:
# Question Q7(a)
# Type your answer here
# Compute mean, median, and standard deviation along each row
mean = np.mean(mat, axis=1)
print(mean)

median = np.median(mat, axis=1)
print(median)

standard = np.std(mat, axis=1)
print(standard)

[12.6 11.   8.2 21.  12.2]
[12. 10.  5. 21. 11.]
[7.70973411 7.21110255 5.26877595 2.44948974 4.79165942]


In [56]:
# Question Q7(b)
# Type your answer here
# Compute mean, median, and standard deviation along each column

mean = np.mean(mat, axis=0)
print("Mean along each column:", mean)

median = np.median(mat, axis=0)
print("Median along each column:", median)

standard = np.std(mat, axis=0)
print("Standard along each column:", standard)

Mean along each column: [10.2 14.6 11.2 18.  11. ]
Median along each column: [ 9. 14. 15. 20.  7.]
Standard along each column: [5.9126982  2.57681975 8.28009662 7.23878443 7.40270221]


In [60]:
# Question Q7(c)
# Type your answer here
# Compute mean, median, and standard deviation for the entire matrix

mean = np.mean(mat)
print("Mean:", mean)

median = np.median(mat)
print("Median:", median)

standard = np.std(mat)
print("Standard:", standard)

Mean: 13.0
Median: 13.0
Standard: 7.211102550927978


#### Q8 - Let use the following command to generate a 2x2 matrix.
####         The student just need to know the application in Python. 
mat = np.arange(1,5).reshape(2,2)
 - (a) Compute the Matrix Transpose
 - (b) Compute the Matrix Power
 - (c) Compute the Matrix Rank
 - (d) Compute the Matrix Detrimental

Reference Notes:
For (a) Transpose is "Flipping" a matrix over its diagonal. The rows and columns get swapped.
https://www.mathsisfun.com/definitions/transpose-matrix-.html

For (b) Raising a matrix to a power involves multiplying the matrix by itself a certain number of times. The power of a matrix is similiar to the concept of exponentiation for numbers.
https://www.mathsisfun.com/algebra/matrix-multiplying.html

For (c) The rank is how many of the rows are "unique": not made of other rows. (Same for columns.)
https://www.mathsisfun.com/algebra/matrix-rank.html

For (d) he determinant is a special number that can be calculated from a matrix
https://www.mathsisfun.com/algebra/matrix-determinant.html

In [62]:
mat = np.arange(1,5).reshape(2,2)
mat

array([[1, 2],
       [3, 4]])

In [63]:
# Question Q8(a)
# Type your answer here

transposed_matrix = np.transpose(mat)
print(transposed_matrix)

[[1 3]
 [2 4]]


In [65]:
# Question Q8(b)
# Raising a matrix to a power involves multiplying the matrix by itself a certain number of times. The power of a matrix is analogous to the concept of exponentiation for numbers.
# Type your answer here
# Specify the power

power = 2
powered_matrix = np.linalg.matrix_power(mat, power)
print(powered_matrix)

[[ 7 10]
 [15 22]]


In [70]:
# Question Q8(c)
# Type your answer here

rank = np.linalg.matrix_rank(mat)
print(rank)

2


In [69]:
# Question Q8(d)
# Type your answer here
# Calculate the determinant

determinant = np.linalg.det(mat)
print(determinant)

-2.0000000000000004


#### Q9 - You are given any array A of shape (3,1) and Array B of shape(4,1).
####         If you add them up using the following code, A + B = C, what will be shape of Array C?
####         Can you explain how the Broadcasting rules are being applied?

In [76]:
# Question Q9
# Type your answer here
A = np.array([[1],[2],[3]])

B = np.array([[10, 20, 30, 40]])

# Broadcasting to perform element-wise addition
print(A.shape)
print(B.shape)

# Print the resulting shape of the A, B and output array
C = A + B
print(C)
print(C.shape)

(3, 1)
(1, 4)
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
(3, 4)


#### Q10 - Change the array of floats to an array of (a) integers and (b) strings. 

arr = np.array([1.3, 2.2, 3.1]) 

In [78]:
# Question 10(a)
# Type your answer here

arr = np.array([1.3, 2.2, 3.1]) 
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [85]:
# Question 10(b)
# Type your answer here

arr = np.array([1.3, 2.2, 3.1])
stringarr = arr.astype('str')
print(stringarr)
print(stringarr.dtype)

['1.3' '2.2' '3.1']
<U32


### Case Studies

#### Question 11
The dataset essentially captures information about different athletes, their ages, the sports they participate in, their physical attributes (weight and height), and a performance metric (score). Below are the columns description:

- athlete: The column represents the name of the athlete participating in sports.
- age: Indicates the age of the athlete.
- sport: Describes the type of sport in which the athlete is involved (e.g., Basketball, Soccer, Swimming).
- weight: Represents the weight of the athlete.
- height: Indicates the height of the athlete.
- score: This column provides a score or performance metric for the athlete in their respective sport.

In [16]:
# Q11
# Type your answer here

# Read the CSV file into a NumPy array
athlete_data = np.genfromtxt('./sports_dataset.csv', delimiter=',', dtype=None, names=True, encoding=None)
# print(athlete_data)
print(athlete_data.shape)

# Print the array to verify the data
print(athlete_data)

(10,)
[('John', 25, 'Basketball', 80, 190, 30)
 ('Alice', 22, 'Soccer', 65, 170, 25) ('Bob', 28, 'Swimming', 75, 180, 35)
 ('Eva', 24, 'Tennis', 68, 175, 28) ('Chris', 30, 'Running', 70, 175, 40)
 ('Sara', 23, 'Basketball', 78, 185, 32)
 ('Mike', 26, 'Soccer', 70, 175, 28) ('Lily', 27, 'Swimming', 73, 178, 38)
 ('Alex', 29, 'Tennis', 72, 180, 33) ('Emma', 24, 'Running', 68, 172, 36)]


In [9]:
for row in athlete_data:
    print(row)

('John', 25, 'Basketball', 80, 190, 30)
('Alice', 22, 'Soccer', 65, 170, 25)
('Bob', 28, 'Swimming', 75, 180, 35)
('Eva', 24, 'Tennis', 68, 175, 28)
('Chris', 30, 'Running', 70, 175, 40)
('Sara', 23, 'Basketball', 78, 185, 32)
('Mike', 26, 'Soccer', 70, 175, 28)
('Lily', 27, 'Swimming', 73, 178, 38)
('Alex', 29, 'Tennis', 72, 180, 33)
('Emma', 24, 'Running', 68, 172, 36)


- (a) Calculate the average age of the athletes.
- (b) Find the athlete with the highest score. Print their name and score.
- (c) Filter and display athletes who participate in Tennis.
- (d) Calculate the average height of athletes who play Basketball.
- (e) Find the athlete with the lowest weight. Print their name and weight.
- (f) Filter and display athletes who are younger than 25 years old.
- (g) Calculate the total score of all athletes.
- (h) Filter and display athletes with a score greater than 30.

In [95]:
print("First athletes recird:", athlete_data[0])

print("All athlete Names:")
for name in athlete_data["athlete"]:
    print(name)
    
Alex_age = athlete_data[0][1]
print("Alex's age is", Alex_age)

basketball_height = athlete_data[athlete_data["sport"]=="Basketball"]["height"]
for value in basketball_height:
    print(value)

First athletes recird: ('John', 25, 'Basketball', 80, 190, 30)
All athlete Names:
John
Alice
Bob
Eva
Chris
Sara
Mike
Lily
Alex
Emma
Alex's age is 25
190
185


In [92]:
# Question 11(a) - Calculate the average age of the athletes
# Type your answer here
average_age = np.mean(athlete_data['age'])
print(f"The average age of the athletes is: {average_age}")

The average age of the athletes is: 25.8


In [98]:
# Question 11(b) - Find the athlete with the highest score. Print their name and score.
# Type your answer here
max_score_index = np.argmax(athlete_data["score"])
print(max_score_index)

highest_scorer = athlete_data['score'][max_score_index]
highest_score = athlete_data['score'][max_score_index]
print(f"The athlete with the hightest socre is {highest_scorer} with a score of {highest_score}")

4
The athlete with the hightest socre is 40 with a score of 40


In [142]:
# Question 11(c) - Filter and display athletes who participate in Tennis.
# Type your answer here
t_athletes = athlete_data[athlete_data["sport"]=="Tennis"]["athlete"]
print(t_athletes)

['Eva' 'Alex']


In [114]:
# Question 11(d) - Calculate the average height of athletes who play Basketball
# Type your answer here
b_average_height = np.mean(athlete_data[athlete_data["sport"]=="Basketball"]["height"])
print("The average height of Basketball players is:", b_average_height)

The average height of Basketball players is: 187.5


In [139]:
# Question 11(e) - Find the athlete with the lowest weight. Print their name and weight.
# Type your answer here

lowest_weight_index = np.argmin(athlete_data["weight"])
print("The lowest weight in athlete:", athlete_data[lowest_weight_index]['weight'])

The lowest weight in athlete: 65


In [145]:
# Question 11(f) - Filter and display athletes who are younger than 25 years old.
# Type your answer here
younger_25 = athlete_data[athlete_data["age"]<25]
print(younger_25)

[('Alice', 22, 'Soccer', 65, 170, 25) ('Eva', 24, 'Tennis', 68, 175, 28)
 ('Sara', 23, 'Basketball', 78, 185, 32)
 ('Emma', 24, 'Running', 68, 172, 36)]


In [156]:
# Question 11(g) - Calculate the total score of all athletes.
# Type your answer here

# print(athlete_data)
total_score = np.sum(athlete_data["score"])
print("The total score of all athletes is: ", total_score)

The total score of all athletes is:  325


In [148]:
# Question 11(h) - Filter and display athletes with a score greater than 30.
# Type your answer here

score_30 = athlete_data[athlete_data["score"]>30]
print(score_30)

[('Bob', 28, 'Swimming', 75, 180, 35)
 ('Chris', 30, 'Running', 70, 175, 40)
 ('Sara', 23, 'Basketball', 78, 185, 32)
 ('Lily', 27, 'Swimming', 73, 178, 38) ('Alex', 29, 'Tennis', 72, 180, 33)
 ('Emma', 24, 'Running', 68, 172, 36)]
