## IT2313 - Programming for Data Science
## Practical 3 
## NumPy for Numerical Computations (Part 1)

### Let try to practise our NumPy knowledge. We will start off with a few simple tasks in this Practical

### Creating NumPy Arrays

#### Q1 - Import NumPy as np

In [2]:
import numpy as np

#### Q2 - Create an array of 10 zeros

In [3]:
# Type your answer here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q3 - Create an array of 10 ones

In [4]:
# Type your answer here
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Q4 - Create an array of 10 fives

In [8]:
# Type your answer here
arr1 = np.ones(10)*5
print(arr1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Q5 - Create an array of the integers from 20 to 40

In [9]:
# Type your answer here
arr2 = np.arange(20,40,1)
print(arr2)
print("total: ", len(arr2))

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
total:  20


#### Q6 - Create an array of all the Even integers from 20 to 40

In [11]:
# Type your answer here
start = 20
end = 40

# start부터 end까지 범위에서 짝수 정수를 생성
even_integers = np.arange(start, end+1, 2)

print(even_integers)


[20 22 24 26 28 30 32 34 36 38 40]


#### Q7 - Create an 10 evenly spaced values from 20 to 40
##### The formula for the step size (step) is calculated as:
##### step = (stop - start) / (num - 1), num is the number of evenly spaced values to generate

In [15]:
# Type your answer here
arr3 = np.linspace(20,39,20)
print(arr3)
print("total: ", len(arr3))

[20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37.
 38. 39.]
total:  20


#### Q8 - Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
# Type your answer here

# Type your answer here
a = np.arange(0,9,1)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q9 - Create a 3x3 matrix with values of 6

In [37]:
# Type your answer here
arr9 = np.ones((3,3))*6
print(arr9)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


#### Q10 - Use NumPy to generate 10 random number between 0 and 1

In [21]:
# Type your answer here
arr10 = np.random.rand(10,)
print(arr10)

[0.15583831 0.69342601 0.37255926 0.53946336 0.33646883 0.91101525
 0.10570753 0.64926529 0.59365457 0.51332484]


#### Q11 - Use NumPy to create the following matrix
#### Note - Use 2 different approaches

In [51]:
# Type your answer here
arr11_a = np.arange(0.01, 1.01, 0.01).reshape((10,10))
print(arr11_a)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [53]:
# Type your answer here
arr11_b = np.linspace(0.01, 1, 100).reshape(10,10)
print(arr11_b)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


### Creating NumPy Indexing and Selection

#### Question 12 - You will be giving a few matrices, and required to to produce the resulting matrix outputs 

In [55]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
# Q12(a)
# Type your answer here
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [57]:
# Q12(b)
# Type your answer here
mat[3,4]

20

In [72]:
# Q12(c)
# Type your answer here
mat[0:3, 1]

array([ 2,  7, 12])

In [68]:
# Q12(e)
# Type your answer here
mat[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [64]:
# Q12(f)
# Type your answer here
mat[4]

array([21, 22, 23, 24, 25])

In [66]:
# Q12(g)
# Type your answer here
mat[3:5,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [77]:
A=np.array([[-2,3], [0,1]])
B=np.array([[8,1], [-5,4]])
print(3*A + 2*B)

[[ 10  11]
 [-10  11]]


#### Q13 - Get the sum of all the values in the matrix

In [82]:
# Type your answer here
mat = np.arange(5,14).reshape(3,3)
mat

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [86]:
# Type your answer here
print(mat.sum())

81


In [87]:
# Type your answer here
np.sum(mat)

81

### Sorting and Filtering of NumPy Arrays

#### Q13 - The medals_2023,csv file contains all the medals won by countries in SEA Games 2023

In [22]:
import csv
csvfile = open("./medals_2023.csv")
for row in csv.reader(csvfile):
    print(row)
csvfile.close()

['Rank', 'Country', 'Gold', 'Silver', 'Bronze', 'Total']
['1', 'Vietnam', '136', '105', '114', '355']
['2', 'Thailand', '108', '96', '109', '313']
['3', 'Indonesia', '87', '80', '109', '276']
['4', 'Cambodia', '81', '74', '127', '282']
['5', 'Philippines', '58', '86', '116', '260']
['6', 'Singapore', '51', '42', '64', '157']
['7', 'Malaysia', '34', '45', '96', '175']
['8', 'Myanmar', '21', '25', '68', '114']
['9', 'Laos', '6', '22', '60', '88']
['10', 'Brunei', '2', '1', '6', '9']
['11', 'Timor-Leste', '0', '0', '8', '8']


#### Q13(a) - Use the data you read from csv file and convert it into NumPy array and display the data type

In [25]:
# Q13(a)
# This array was created
medals = [
    ['Rank', 'Country', 'Gold', 'Silver', 'Bronze', 'Total'],
    ['1', 'Vietnam', '136', '105', '114', '355'],
    ['2', 'Thailand', '108', '96', '109', '313'],
    ['3', 'Indonesia', '87', '80', '109', '276'],
    ['4', 'Cambodia', '81', '74', '127', '282'],
    ['5', 'Philippines', '58', '86', '116', '260'],
    ['6', 'Singapore', '51', '42', '64', '157'],
    ['7', 'Malaysia', '34', '45', '96', '175'],
    ['8', 'Myanmar', '21', '25', '68', '114'],
    ['9', 'Laos', '6', '22', '60', '88'],
    ['10', 'Brunei', '2', '1', '6', '9'],
    ['11', 'Timor-Leste', '0', '0', '8', '8']
]

# Convert the data to NumPy array
# Type your answer here
data = np.array(medals[:], dtype=object)
# 숫자, 문자열, 리스트 등 여러 다양한 데이터 타입을 가질 수 있을 때 dtype=object를 사용할 수 있습니다.

# Print the NumPy array
# Type your answer here
print("Data as NumPy array:")
print(data)

Data as NumPy array:
[['Rank' 'Country' 'Gold' 'Silver' 'Bronze' 'Total']
 ['1' 'Vietnam' '136' '105' '114' '355']
 ['2' 'Thailand' '108' '96' '109' '313']
 ['3' 'Indonesia' '87' '80' '109' '276']
 ['4' 'Cambodia' '81' '74' '127' '282']
 ['5' 'Philippines' '58' '86' '116' '260']
 ['6' 'Singapore' '51' '42' '64' '157']
 ['7' 'Malaysia' '34' '45' '96' '175']
 ['8' 'Myanmar' '21' '25' '68' '114']
 ['9' 'Laos' '6' '22' '60' '88']
 ['10' 'Brunei' '2' '1' '6' '9']
 ['11' 'Timor-Leste' '0' '0' '8' '8']]


#### Q13(b) - Only Display the Top 3 medal ranking countries

In [94]:
# Q13(b)
# Type your answer here
# Extract the header and the top 3 rows
header = data[0]
top_3 = data[1:4]

# Print the header and top 3 countries
print(header, top_3)

['Rank' 'Country' 'Gold' 'Silver' 'Bronze' 'Total'] [['1' 'Vietnam' '136' '105' '114' '355']
 ['2' 'Thailand' '108' '96' '109' '313']
 ['3' 'Indonesia' '87' '80' '109' '276']]


#### Q13(c) - Display all the medals won by Singapore

In [28]:
# Q13(c)
# Type your answer here
# Create a boolean mask for rows where 'Country' is 'Singapore'
country_list = data[:, 1]
# print(country_list)

# Use boolean indexing to extract the rows for Singapore
is_Singapore = country_list=="Singapore"

# Print the medals won by Singapore
print(data[0])
print(data[is_Singapore])

['Rank' 'Country' 'Gold' 'Silver' 'Bronze' 'Total']
[['6' 'Singapore' '51' '42' '64' '157']]


#### Q13(d) - Display only the Gold and Total Medals won by the Countries

In [30]:
# Q13(d)
# Type your answer here
# Keep 'Rank', 'Country', 'Gold', and 'Total' columns

selected_columns = data[:, [0,1,2,5]]

# Print the selected columns for all countries

print(selected_columns)

[['Rank' 'Country' 'Gold' 'Total']
 ['1' 'Vietnam' '136' '355']
 ['2' 'Thailand' '108' '313']
 ['3' 'Indonesia' '87' '276']
 ['4' 'Cambodia' '81' '282']
 ['5' 'Philippines' '58' '260']
 ['6' 'Singapore' '51' '157']
 ['7' 'Malaysia' '34' '175']
 ['8' 'Myanmar' '21' '114']
 ['9' 'Laos' '6' '88']
 ['10' 'Brunei' '2' '9']
 ['11' 'Timor-Leste' '0' '8']]


#### Q13(e) Remove the Silver and Bronze column

In [31]:
# Q13(e)
# Type your answer here
# Remove 'Silver' and 'Bronze' columns (columns 3 and 4)
numpy_array = np.delete(data, [3,4], axis=1)

# Print the modified NumPy array
print(numpy_array)

[['Rank' 'Country' 'Gold' 'Total']
 ['1' 'Vietnam' '136' '355']
 ['2' 'Thailand' '108' '313']
 ['3' 'Indonesia' '87' '276']
 ['4' 'Cambodia' '81' '282']
 ['5' 'Philippines' '58' '260']
 ['6' 'Singapore' '51' '157']
 ['7' 'Malaysia' '34' '175']
 ['8' 'Myanmar' '21' '114']
 ['9' 'Laos' '6' '88']
 ['10' 'Brunei' '2' '9']
 ['11' 'Timor-Leste' '0' '8']]


#### Q13(f) - Sort the Medal Tally Table based on the Total Medals won by countries

In [51]:
# Q13(f)

import numpy as np

medals = [
    ['Rank', 'Country', 'Gold', 'Silver', 'Bronze', 'Total'],
    ['2', 'Thailand', '108', '96', '109', '313'],
    ['1', 'Vietnam', '136', '105', '114', '355'],
    ['3', 'Indonesia', '87', '80', '109', '276'],
    ['4', 'Cambodia', '81', '74', '127', '282'],
    ['5', 'Philippines', '58', '86', '116', '260'],
    ['6', 'Singapore', '51', '42', '64', '157'],
    ['7', 'Malaysia', '34', '45', '96', '175'],
    ['8', 'Myanmar', '21', '25', '68', '114'],
    ['9', 'Laos', '6', '22', '60', '88'],
    ['10', 'Brunei', '2', '1', '6', '9'],
    ['11', 'Timor-Leste', '0', '0', '8', '8']
]

numpy_array = np.array(medals[1:], dtype=object)

# Convert 'Total' column to integers for sorting
# Type your answer here
total_column = numpy_array[:, -1].astype(int)

# Get indices that would sort the 'Total' column in descending order
# Type your answer here
sorted_indices = np.argsort(total_column)[::-1]
print(sorted_indices)

# Sort the NumPy array based on the sorted indices
# Type your answer here
sorted_array = numpy_array[sorted_indices]

# Add the header row back to the sorted array
# Type your answer here
sorted_array = np.vstack([medals[0], sorted_array])

# Print the sorted NumPy array
# Type your answer here
print(sorted_array)

[ 1  0  3  2  4  6  5  7  8  9 10]
[['Rank' 'Country' 'Gold' 'Silver' 'Bronze' 'Total']
 ['1' 'Vietnam' '136' '105' '114' '355']
 ['2' 'Thailand' '108' '96' '109' '313']
 ['4' 'Cambodia' '81' '74' '127' '282']
 ['3' 'Indonesia' '87' '80' '109' '276']
 ['5' 'Philippines' '58' '86' '116' '260']
 ['7' 'Malaysia' '34' '45' '96' '175']
 ['6' 'Singapore' '51' '42' '64' '157']
 ['8' 'Myanmar' '21' '25' '68' '114']
 ['9' 'Laos' '6' '22' '60' '88']
 ['10' 'Brunei' '2' '1' '6' '9']
 ['11' 'Timor-Leste' '0' '0' '8' '8']]


In [52]:
# Q13(f)

import numpy as np

medals = [
    ['Rank', 'Country', 'Gold', 'Silver', 'Bronze', 'Total'],
    ['1', 'Vietnam', '136', '105', '114', '355'],
    ['2', 'Thailand', '108', '96', '109', '313'],
    ['3', 'Indonesia', '87', '80', '109', '276'],
    ['4', 'Cambodia', '81', '74', '127', '282'],
    ['5', 'Philippines', '58', '86', '116', '260'],
    ['6', 'Singapore', '51', '42', '64', '157'],
    ['7', 'Malaysia', '34', '45', '96', '175'],
    ['8', 'Myanmar', '21', '25', '68', '114'],
    ['9', 'Laos', '6', '22', '60', '88'],
    ['10', 'Brunei', '2', '1', '6', '9'],
    ['11', 'Timor-Leste', '0', '0', '8', '8']
]

# Convert the data to NumPy array, excluding the first row
# Type your answer here
numpy_array = np.array(medals[1:], dtype=object)

# Remove 'Silver' and 'Bronze' columns (columns 3 and 4)
# Type your answer here
numpy_array = np.delete(numpy_array, [3, 4], axis=1)

# Convert 'Total' column to integers for sorting
# Type your answer here
total_column = numpy_array[:, -1].astype(int)

# Get indices that would sort the 'Total' column in descending order
# Type your answer here
sorted_indices = np.argsort(total_column)[::-1]

# Sort the NumPy array based on the sorted indices
# Type your answer here
sorted_array = numpy_array[sorted_indices]

# Add the header row back to the sorted array
# Type your answer here
sorted_array = np.vstack([medals[0][:3] + medals[0][-1:], sorted_array])

# Print the sorted NumPy array without 'Silver' and 'Bronze'
# Type your answer here
print(sorted_array)

[['Rank' 'Country' 'Gold' 'Total']
 ['1' 'Vietnam' '136' '355']
 ['2' 'Thailand' '108' '313']
 ['4' 'Cambodia' '81' '282']
 ['3' 'Indonesia' '87' '276']
 ['5' 'Philippines' '58' '260']
 ['7' 'Malaysia' '34' '175']
 ['6' 'Singapore' '51' '157']
 ['8' 'Myanmar' '21' '114']
 ['9' 'Laos' '6' '88']
 ['10' 'Brunei' '2' '9']
 ['11' 'Timor-Leste' '0' '8']]
